version: '3'

services:

  postgres:
    image: postgres:10.5
    container_name: people_postgres
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data